### PR TITLE
PUB-1166 added BtT to template and extended all components need from it

### PR DESCRIPTION
**Pull request by kurt-uk**
### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-1166

### Change description ###
added BtT to template and extended all components need from it and fixed cookie naming 
BtT appears on most pages, the look is the same
Screenshot 2022-03-15 at 14 46 51
Screenshot 2022-03-15 at 14 47 03

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by furnivall — DISMISSED** [review]

**Review by alberto-hortiguela — DISMISSED** [review]

**Review by commitBlob — DISMISSED** [review]
mkovb

**Review by marcogagliardi — CHANGES_REQUESTED** [review]
Can we use the parent-box wrapper in the template so we don't need to have it in each page?

**Comment by kurt-uk** [comment]
> Can we use the parent-box wrapper in the template so we don't need to have it in each page?

unfortunately not, that would only work on about 15% of our pages, as each page is done slightly differently in how its holds context of its content, some of the pages such as the alphabetical search page would work, where the content isnt isolated. The rest of our pages though contain their content in a way where if we exclude the parent box from the content (as putting the div in the template would mean as you cant then inject the content mid way in the template) the 2 are treated as separate entities and doesnt display properly

**Comment by alberto-hortiguela** [comment]
Conflict issues

**Review by alberto-hortiguela — DISMISSED** [review]

**Review by commitBlob — APPROVED** [review]

**Review by ChrisS1512 — APPROVED** [review]
Looks good. Just needs updating with base branch

**Review by alberto-hortiguela — DISMISSED** [review]

**Review by ChrisS1512 — DISMISSED** [review]

**Review by ChrisS1512 — APPROVED** [review]

**Review by joshblackmoor — APPROVED** [review]

**Review by ChrisS1512 — APPROVED** [review]

**Review by furnivall — APPROVED** [review]

**Pull request merged**
