### PR TITLE
PUB-956 - SJP Cases Subscription Option

### PR DESCRIPTION
**Pull request by commitBlob**
### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-956

### Change description ###
- include new table (National lists) with SJP cases checkbox (id: 0 as per agreement with Kurt and Nigel)
- add additional tests
- update existing tests

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```
Capture7

### CODE REVIEW

**Review by alberto-hortiguela — DISMISSED** [review]
LGTM

**Review by furnivall — DISMISSED** [review]
this looks good 👍

**Review by furnivall — APPROVED** [review]
🥇

**Review by alberto-hortiguela — APPROVED** [review]
LGTM

**Pull request merged**
