### PR TITLE
PUB-968 - Input error

### PR DESCRIPTION
**Pull request by commitBlob**
### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-968

### Change description ###
Removed black border on the input after error is displayed

**NOTE:**
For this changes to take effect please run yarn build to rebuild css
Includes PUB-971 changes (#205) which were merged into master

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```
error

### CODE REVIEW

**Review by alberto-hortiguela — DISMISSED** [review]
LGTM

**Review by alberto-hortiguela — DISMISSED** [review]
LGTM

**Review by kurt-uk — APPROVED** [review]

**Review by alberto-hortiguela — APPROVED** [review]
LGTM

**Review by marcogagliardi — APPROVED** [review]
👌🏽

**Review by junaidiqbalmoj — APPROVED** [review]
👍

**Pull request merged**
