### PR TITLE
PUB-856 Altered header text, added header and gov.uk links

### PR DESCRIPTION
**Pull request by furnivall**
### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-856

### Change description ###
Header text and link amended, gov.uk link added to logo.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

### CODE REVIEW

**Review by kurt-uk — CHANGES_REQUESTED** [review]
can you add some unit tests in there just to cover these additions

**Review by marcogagliardi — APPROVED** [review]
👌🏽

**Comment by furnivall** [comment]
> can you add some unit tests in there just to cover these additions

Should be done now

**Review by commitBlob — APPROVED** [review]

**Comment by furnivall** [comment]
> can you add some unit tests in there just to cover these additions

Should be done now

**Review by kurt-uk — APPROVED** [review]
👍🏼

**Pull request merged**
